<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

// Implements HOOK_form_alter
function citizen_preview_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add the js library button to the node edit form
  if (isset($form["actions"]["preview"])) {
    $form['#attached']['library'][] = 'citizen_preview/preview';
    $form['actions']['citizen_preview'] = [
      '#type' => 'link',
      '#title' => t('Preview'),
      '#url' => Url::fromRoute('citizen_preview.form'),
      '#attributes' => [
        'class' => [
          'fixed-preview',
          'button',
          'button--primary'
        ],
      ],
    ];
  }
}
